/* Edge Journal - local-first prototype. Cloud sync requires Supabase configuration + RLS. */
const $ = (id) => document.getElementById(id);
const STORAGE_KEY = 'edgeJournal.trades.v1';
const REVIEW_KEY = 'edgeJournal.reviews.v1';
const GITHUB_CONFIG_KEY = 'edgeJournal.githubConfig.v1';
const GITHUB_DATA_PATH = '.edge-journal/journal.json';
let githubSyncTimer = null;
let githubSyncBusy = false;
let githubSyncPaused = false;
let trades = readStore(STORAGE_KEY, []);
let reviews = readStore(REVIEW_KEY, []);
let currentImageData = '';
let marketCoins = [];
let marketLoading = false;
let watchedCoins = readStore('edgeJournal.watchlist.v1', []);
let toastTimer;

function readStore(key, fallback) { try { const v = JSON.parse(localStorage.getItem(key)); return Array.isArray(v) ? v : fallback; } catch { return fallback; } }
function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(trades)); localStorage.setItem(REVIEW_KEY, JSON.stringify(reviews)); $('lastSaved').textContent = 'Saved locally · ' + new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}); $('storageDot').style.background = 'var(--green)'; $('storageStatus').textContent = 'Local storage saved'; const cfg=getGitHubConfig(); if(cfg?.token&&cfg?.owner&&cfg?.repo&&cfg?.branch){$('syncText').textContent='Saved locally · GitHub sync queued'; scheduleGitHubSync();}else{$('syncText').textContent='Saved in this browser. Configure GitHub to sync across devices.';} return true; } catch (e) { toast('Could not save. Storage may be full; remove a large screenshot or export your data.'); return false; } }
function getGitHubConfig(){try{return JSON.parse(localStorage.getItem(GITHUB_CONFIG_KEY)||'null')}catch{return null}}
function repoUrl(cfg=getGitHubConfig()){return cfg?.owner&&cfg?.repo?`https://github.com/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}`:'https://github.com/'}
function setGitHubStatus(message,state='neutral'){const el=$('githubStatus');if(!el)return;el.className='github-status '+state;el.innerHTML=`<span class="github-status-dot"></span><span>${esc(message)}</span>`;}
function fillGitHubForm(){const c=getGitHubConfig()||{};$('ghToken').value=c.token||'';$('ghOwner').value=c.owner||'faizfirdaus505';$('ghRepo').value=c.repo||'trade-journal';$('ghBranch').value=c.branch||'main';$('ghPagesUrl').value=c.pagesUrl||'';if(c.token&&c.owner&&c.repo){setGitHubStatus(`Konfigurasi tersimpan untuk ${c.owner}/${c.repo} · branch ${c.branch||'main'}.`, 'connected')}else setGitHubStatus('Belum terhubung. Isi token dan detail repository untuk mulai.');}
function readGitHubForm(){return {token:$('ghToken').value.trim(),owner:$('ghOwner').value.trim(),repo:$('ghRepo').value.trim(),branch:$('ghBranch').value.trim()||'main',pagesUrl:$('ghPagesUrl').value.trim()};}
function validateGitHubConfig(c){if(!c.token||!c.owner||!c.repo||!c.branch){throw new Error('Token, username, repository, dan branch wajib diisi.');}if(!/^[a-zA-Z0-9-]+$/.test(c.owner)||! /^[a-zA-Z0-9._-]+$/.test(c.repo)){throw new Error('Format username atau nama repository tidak valid.');}}
async function githubApi(path, cfg=getGitHubConfig(), options={}){if(!cfg?.token)throw new Error('Token GitHub belum diisi.');const response=await fetch('https://api.github.com'+path,{...options,headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+cfg.token,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok){const message=data.message||`GitHub API error (${response.status})`;throw new Error(response.status===401?'Token ditolak. Periksa token dan izin akses.':response.status===403?'Akses ditolak atau batas API tercapai. Periksa izin token.':response.status===404?'Repository/branch tidak ditemukan atau token tidak memiliki akses.':message);}return data;}
async function testGitHubConnection(cfg=readGitHubForm()){validateGitHubConfig(cfg);setGitHubStatus('Memeriksa token, akun, repository, dan branch…','loading');const user=await githubApi('/user',cfg);const repo=await githubApi(`/repos/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}`,cfg);if(repo.default_branch!==cfg.branch){try{await githubApi(`/repos/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}/branches/${encodeURIComponent(cfg.branch)}`,cfg)}catch{throw new Error(`Branch “${cfg.branch}” tidak ditemukan. Branch default repository ini adalah “${repo.default_branch}”.`);}}setGitHubStatus(`Terhubung sebagai @${user.login} · ${repo.full_name} · branch ${cfg.branch}.`,'connected');return {user,repo};}
function scheduleGitHubSync(){if(githubSyncPaused||!getGitHubConfig()?.token)return;clearTimeout(githubSyncTimer);githubSyncTimer=setTimeout(()=>syncJournalToGitHub(false),1800);}
function encodeBase64Unicode(value){const bytes=new TextEncoder().encode(value);let binary='';for(let i=0;i<bytes.length;i++)binary+=String.fromCharCode(bytes[i]);return btoa(binary)}
function decodeBase64Unicode(value){const binary=atob(value.replace(/\n/g,''));const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function getGitHubJournal(cfg){const path='/repos/'+encodeURIComponent(cfg.owner)+'/'+encodeURIComponent(cfg.repo)+'/contents/'+GITHUB_DATA_PATH.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(cfg.branch);try{return await githubApi(path,cfg)}catch(e){if(String(e.message).includes('tidak ditemukan')||String(e.message).includes('Not Found'))return null;throw e;}}
async function syncJournalToGitHub(showToast=true){const cfg=getGitHubConfig();if(!cfg?.token||githubSyncBusy)return;githubSyncBusy=true;try{const existing=await getGitHubJournal(cfg);const payload={app:'Edge Journal',version:1,updatedAt:new Date().toISOString(),s,reviews};const body={message:'Sync Edge Journal records',content:encodeBase64Unicode(JSON.stringify(payload,null,2)),branch:cfg.branch};if(existing?.sha)body.sha=existing.sha;await githubApi(`/repos/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}/contents/${GITHUB_DATA_PATH.split('/').map(encodeURIComponent).join('/')}`,cfg,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('storageStatus').textContent='GitHub connected';$('storageDot').style.background='var(--green)';$('syncText').textContent='Synced with GitHub · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('lastSaved').textContent='Saved locally + GitHub · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});if(showToast)toast('Journal berhasil disinkronkan ke GitHub.');return true;}catch(e){$('storageStatus').textContent='GitHub sync issue';$('storageDot').style.background='var(--orange)';$('syncText').textContent='Local save OK · GitHub sync failed';setGitHubStatus(e.message,'error');if(showToast)toast('Sinkronisasi GitHub gagal: '+e.message);return false;}finally{githubSyncBusy=false;}}
function mergeById(local,remote){const map=new Map();(remote||[]).forEach(x=>map.set(x.id||uid(),x));(local||[]).forEach(x=>map.set(x.id||uid(),x));return [...map.values()]}
async function syncJournalFromGitHub({quiet=false}={}){const cfg=getGitHubConfig();if(!cfg?.token)return false;try{const remote=await getGitHubJournal(cfg);if(!remote){await syncJournalToGitHub(!quiet);return true;}const data=JSON.parse(decodeBase64Unicode(remote.content||''));if(!Array.isArray(data.s)||!Array.isArray(data.reviews))throw new Error('Format file jurnal di repository tidak valid.');const hadLocal=s.length||reviews.length;trades=hadLocal?mergeById(trades,data.trades):data.trades;reviews=hadLocal?mergeById(reviews,data.reviews):data.reviews;githubSyncPaused=true;localStorage.setItem(STORAGE_KEY,JSON.stringify(trades));localStorage.setItem(REVIEW_KEY,JSON.stringify(reviews));githubSyncPaused=false;renderAll();if(hadLocal){await syncJournalToGitHub(false);}else{$('storageStatus').textContent='GitHub connected';$('storageDot').style.background='var(--green)';$('syncText').textContent='Loaded journal from GitHub · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}if(!quiet)toast('Jurnal berhasil diambil dari GitHub.');return true;}catch(e){githubSyncPaused=false;setGitHubStatus('Sinkronisasi gagal: '+e.message,'error');if(!quiet)toast('Tidak dapat mengambil jurnal dari GitHub: '+e.message);return false;}}
function openGitHubSettings(){fillGitHubForm();$('githubDialog').showModal();}
async function saveGitHubSettings(e){e.preventDefault();const cfg=readGitHubForm();try{validateGitHubConfig(cfg);if(!cfg.pagesUrl)cfg.pagesUrl='';localStorage.setItem(GITHUB_CONFIG_KEY,JSON.stringify(cfg));await testGitHubConnection(cfg);$('githubDialog').close();$('githubBtn').innerHTML='⚙ Pengaturan GitHub <span>↗</span>'; $('githubOpenBtn').innerHTML='◉ Buka Repository <span>↗</span>';if(!trades.length&&!reviews.length){await syncJournalFromGitHub({quiet:true});}else{await syncJournalToGitHub(false);}toast('Pengaturan GitHub tersimpan. Sinkronisasi aktif di browser ini.');}catch(err){setGitHubStatus(err.message,'error');toast('Koneksi GitHub gagal: '+err.message);}}

function uid() { return Date.now().toString(36) + Math.random().toString(36).slice(2,8); }
function num(v) { const n = Number(v); return Number.isFinite(n) ? n : 0; }
function money(v, digits=2) { return (v < 0 ? '-$' : '$') + Math.abs(v).toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits}); }
function pct(v) { return (v > 0 ? '+' : '') + v.toFixed(2) + '%'; }
function esc(s='') { return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function dateFmt(s) { if (!s) return '—'; const d = new Date(s + (s.length===10?'T12:00:00':'')); return Number.isNaN(+d) ? s : d.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'2-digit'}); }
function closedTrades() { return trades.filter(t => t.status === 'Closed' && t.exit !== '' && t.exit !== null && Number.isFinite(Number(t.netPnl))); }
function calcPnl(t) { if (t.manualPnl !== '' && t.manualPnl !== null && t.manualPnl !== undefined && Number.isFinite(Number(t.manualPnl))) return Number(t.manualPnl); if (t.status !== 'Closed' || t.exit === '' || t.exit === null) return null; const diff = (num(t.exit)-num(t.entry)) * num(t.qty) * (t.side === 'Short' ? -1 : 1); return diff - num(t.fees); }
function resultOf(t) { const p = calcPnl(t); return p === null ? 'Open' : p > 0.0000001 ? 'Win' : p < -0.0000001 ? 'Loss' : 'Breakeven'; }
function rMultiple(t) { const p = calcPnl(t); const r = num(t.risk); return p === null || r <= 0 ? null : p / r; }
function toast(msg) { const el=$('toast'); el.textContent=msg; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),3000); }
function navigate(view) { document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`)); document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); const titles={dashboard:'Dashboard',trades:'Trade journal',market:'Top market',analytics:'Analytics',reviews:'Daily review',risk:'Risk calculator'}; $('crumbTitle').textContent=titles[view]||'Dashboard'; $('sidebar').classList.remove('open'); if(view==='dashboard') renderDashboard(); if(view==='trades') renderTrades(); if(view==='analytics') renderAnalytics(); if(view==='reviews') renderReviews(); if(view==='market'&&!marketCoins.length) loadMarket(); window.scrollTo({top:0,behavior:'smooth'}); }
function iconClass(pair) { const p=(pair||'').toUpperCase(); if(p.startsWith('BTC'))return 'btc'; if(p.startsWith('ETH'))return 'eth'; return 'other'; }
function pairSymbol(pair) { const p=(pair||'?').toUpperCase(); return p.startsWith('BTC')?'₿':p.startsWith('ETH')?'◆':p.charAt(0); }
function pnlClass(p) { return p>0?'pnl-positive':p<0?'pnl-negative':'pnl-neutral'; }
function tradeRow(t, recent=false) { const p=calcPnl(t), res=resultOf(t); const pair=esc(t.pair||'Unknown'); const setup=esc(t.setup||'Unspecified setup'); return `<tr><td><div class="coin-cell"><span class="coin-icon ${iconClass(t.pair)}">${esc(pairSymbol(t.pair))}</span><span><b>${pair}</b><small>${setup}</small></span></div></td><td><span class="tag ${t.side==='Short'?'short':'long'}">${esc(t.side||'Long')}</span></td>${recent?`<td>${setup}</td>`:`<td>${esc(t.entry||'—')} → ${esc(t.exit||'—')}</td>`}<td>${dateFmt(t.date)}</td>${recent?'':`<td>${rMultiple(t)===null?'—':(rMultiple(t)>0?'+':'')+rMultiple(t).toFixed(2)+'R'}</td>`}<td class="${p===null?'pnl-neutral':pnlClass(p)}">${p===null?'—':(p>0?'+':'')+money(p)}</td><td><span class="tag ${res==='Open'?'open':res==='Win'?'win':res==='Loss'?'loss':'closed'}">${res==='Breakeven'?'Flat':res}</span></td>${recent?'':`<td><button class="text-button edit-trade" data-id="${esc(t.id)}">Edit</button></td>`}</tr>`; }
function renderDashboard() { const closed=closedTrades().slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.createdAt||0)-(b.createdAt||0)); const wins=closed.filter(t=>calcPnl(t)>0), losses=closed.filter(t=>calcPnl(t)<0), bes=closed.filter(t=>calcPnl(t)===0); const gp=wins.reduce((s,t)=>s+calcPnl(t),0), gl=Math.abs(losses.reduce((s,t)=>s+calcPnl(t),0)), net=closed.reduce((s,t)=>s+calcPnl(t),0), startBalance=400, returnPct=net/startBalance*100; $('statPnl').textContent=(net>0?'+':'')+money(net); $('statPnl').className='stat-value '+pnlClass(net); $('statPnlPct').textContent=pct(returnPct); $('statWins').textContent=`${wins.length} wins / ${losses.length} losses`; $('statWin').textContent=closed.length?((wins.length/closed.length)*100).toFixed(1)+'%':'—'; $('statPF').textContent=gl? (gp/gl).toFixed(2) : gp>0?'∞':'—'; let equity=0, peak=0, maxDD=0; const points=[]; closed.forEach(t=>{equity+=calcPnl(t);peak=Math.max(peak,equity);if(peak>0)maxDD=Math.max(maxDD,(peak-equity)/peak*100);points.push(equity)}); $('statDD').textContent=maxDD.toFixed(2)+'%'; $('chartTotal').textContent=(net>0?'+':'')+money(net); $('chartCaption').textContent=closed.length?`${closed.length} closed trade${closed.length===1?'':'s'}`:'No closed trades yet'; $('donutTotal').textContent=closed.length; $('donutWins').textContent=wins.length; $('donutLosses').textContent=losses.length; $('donutBE').textContent=bes.length; const total=Math.max(closed.length,1); const a=wins.length/total*360,b=a+losses.length/total*360; $('outcomeDonut').style.background=`conic-gradient(var(--green) 0deg ${a}deg,var(--red) ${a}deg ${b}deg,var(--orange) ${b}deg 360deg)`; drawEquity(points); const recent=trades.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt||0)-(a.createdAt||0)).slice(0,5); $('recentTradesBody').innerHTML=recent.map(t=>tradeRow(t,true)).join(''); $('recentEmpty').classList.toggle('show',recent.length===0); $('tradeCountBadge').textContent=trades.length; const tracked=trades.filter(t=>t.status==='Closed'&&t.rules!=='Not set'); const adherent=tracked.filter(t=>t.rules==='Yes'||t.rules==='Mostly'); const d=tracked.length?Math.round(adherent.length/tracked.length*100):null; $('disciplineValue').innerHTML=d===null?'—':' '+d+'%<small> adherence</small>'; $('disciplineBar').style.width=(d||0)+'%'; $('disciplineNote').textContent=d===null?'Log rule compliance in each trade to see this metric.':`${adherent.length} of ${tracked.length} recorded closed trades were marked as following your plan.`; }
function drawEquity(points) { const svg=$('equityChart'); if(!points.length){svg.innerHTML='<text x="360" y="110" text-anchor="middle" fill="#7d8792" font-size="12">Add closed trades to build your curve</text>';return;} const W=720,H=220,pad=18,min=Math.min(0,...points),max=Math.max(0,...points),range=max-min||1; const coords=points.map((v,i)=>[pad+(points.length===1?0:i/(points.length-1))*(W-pad*2),H-pad-((v-min)/range)*(H-pad*2)]); const line=coords.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' '); const area=line+` L ${coords[coords.length-1][0]} ${H-pad} L ${coords[0][0]} ${H-pad} Z`; const color=points[points.length-1]>=0?'#68d69b':'#ff8585'; const y0=H-pad-(0-min)/range*(H-pad*2); svg.innerHTML=`<defs><linearGradient id="eqfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity=".22"/><stop offset="100%" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><line x1="0" y1="${y0}" x2="720" y2="${y0}" stroke="#29323a" stroke-dasharray="4 5"/><path d="${area}" fill="url(#eqfill)"/><path d="${line}" fill="none" stroke="${color}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>${coords.length<50?coords.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="2.5" fill="${color}"/>`).join(''):''}`; }
function renderTrades() { const q=$('tradeSearch').value.trim().toLowerCase(), side=$('filterSide').value, status=$('filterStatus').value, result=$('filterResult').value; const list=trades.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt||0)-(a.createdAt||0)).filter(t=>(!q||[t.pair,t.setup,t.notes,t.side].join(' ').toLowerCase().includes(q))&&(side==='all'||t.side===side)&&(status==='all'||t.status===status)&&(result==='all'||resultOf(t)===result)); $('tradesBody').innerHTML=list.map(t=>tradeRow(t,false)).join(''); $('tradesEmpty').classList.toggle('show',list.length===0); $('tradeFootCount').textContent=`${list.length} of ${trades.length} trades`; document.querySelectorAll('.edit-trade').forEach(b=>b.addEventListener('click',()=>openTrade(b.dataset.id))); }
function renderAnalytics() { const c=closedTrades(),p=c.map(calcPnl),wins=p.filter(x=>x>0),losses=p.filter(x=>x<0),sum=p.reduce((a,b)=>a+b,0),rs=c.map(rMultiple).filter(x=>x!==null); $('anaExpectancy').textContent=c.length?money(sum/c.length):'—'; $('anaAvgWin').textContent=wins.length?money(wins.reduce((a,b)=>a+b,0)/wins.length):'—'; $('anaAvgLoss').textContent=losses.length?money(losses.reduce((a,b)=>a+b,0)/losses.length):'—'; $('anaAvgR').textContent=rs.length?(rs.reduce((a,b)=>a+b,0)/rs.length).toFixed(2)+'R':'—'; const setups={}; c.forEach(t=>{const k=t.setup||'Unspecified';setups[k]=(setups[k]||0)+calcPnl(t)}); const pairs=Object.entries(setups).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])); const max=Math.max(1,...pairs.map(x=>Math.abs(x[1]))); $('setupBreakdown').innerHTML=pairs.length?pairs.map(([name,val])=>`<div class="setup-row"><div class="setup-row-head"><span>${esc(name)}</span><b class="${pnlClass(val)}">${val>0?'+':''}${money(val)}</b></div><div class="bar-track"><span style="width:${Math.max(2,Math.abs(val)/max*100)}%;background:${val<0?'var(--red)':'var(--green)'}"></span></div></div>`).join(''):'<div class="review-empty">Record closed trades with setup names to compare strategies.</div>'; $('sideBreakdown').innerHTML=['Long','Short'].map(side=>{const arr=c.filter(t=>t.side===side),v=arr.reduce((s,t)=>s+calcPnl(t),0);return `<div class="side-item"><span class="side-symbol">${side==='Long'?'↗':'↘'}</span><div><b>${side}</b><small>${arr.length} closed trade${arr.length===1?'':'s'}</small></div><strong class="${pnlClass(v)}">${v>0?'+':''}${money(v)}</strong></div>`}).join(''); let eq=0,peak=0,dd=0; c.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')).forEach(t=>{eq+=calcPnl(t);peak=Math.max(peak,eq);if(peak>0)dd=Math.max(dd,(peak-eq)/peak*100)}); const gp=wins.reduce((a,b)=>a+b,0),gl=Math.abs(losses.reduce((a,b)=>a+b,0)); const rows=[['Total trades',c.length],['Winning trades',wins.length],['Losing trades',losses.length],['Breakeven trades',p.filter(x=>x===0).length],['Gross profit',money(gp)],['Gross loss',money(gl)],['Profit factor',gl?(gp/gl).toFixed(2):gp>0?'∞':'—'],['Max drawdown',dd.toFixed(2)+'%'],['Total recorded trades',trades.length],['Open trades',trades.filter(t=>t.status==='Open').length]]; $('statsList').innerHTML=rows.map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join(''); }
function renderReviews() { $('reviewCount').textContent=`${reviews.length} ENTRIES`; const list=reviews.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')); $('reviewHistory').innerHTML=list.length?list.map(r=>`<div class="review-entry"><div class="review-entry-top"><b>${dateFmt(r.date)} · ${esc(r.mood)}</b><span>${esc(r.adherence)}</span></div>${r.mistake&&r.mistake!=='None identified'?`<p><b>Focus:</b> ${esc(r.mistake)}</p>`:''}${r.good?`<p><b>Went well:</b> ${esc(r.good)}</p>`:''}${r.improve?`<p><b>Improve:</b> ${esc(r.improve)}</p>`:''}${r.lesson?`<p><b>Lesson:</b> ${esc(r.lesson)}</p>`:''}<div class="review-actions"><button data-edit-review="${esc(r.id)}">Edit</button><button data-delete-review="${esc(r.id)}">Delete</button></div></div>`).join(''):'<div class="review-empty">No reviews yet. Start with one lesson from today.</div>'; document.querySelectorAll('[data-edit-review]').forEach(b=>b.onclick=()=>editReview(b.dataset.editReview)); document.querySelectorAll('[data-delete-review]').forEach(b=>b.onclick=()=>{if(confirm('Delete this review?')){reviews=reviews.filter(r=>r.id!==b.dataset.deleteReview);persist();renderReviews();toast('Review deleted.')}}); }
function clearTradeForm() { $('tradeForm').reset(); $('tradeId').value=''; $('tradeModalTitle').textContent='Add new trade'; $('deleteTradeBtn').classList.add('hidden'); $('tradeDate').value=new Date().toISOString().slice(0,10); $('tradeLeverage').value='1'; $('tradeFees').value='0'; $('tradeManualPnl').value=''; $('tradeRisk').value=''; currentImageData=''; $('imagePreview').hidden=true; $('imagePreview').src=''; }
function openTrade(id='') { clearTradeForm(); if(id){const t=trades.find(x=>x.id===id);if(!t)return; $('tradeModalTitle').textContent='Edit trade';$('deleteTradeBtn').classList.remove('hidden'); const map={tradeId:'id',tradePair:'pair',tradeMarket:'market',tradeSide:'side',tradeStatus:'status',tradeSetup:'setup',tradeTimeframe:'timeframe',tradeEntry:'entry',tradeExit:'exit',tradeQty:'qty',tradeLeverage:'leverage',tradeStop:'stop',tradeTarget:'target',tradeFees:'fees',tradeManualPnl:'manualPnl',tradeRisk:'risk',tradeDate:'date',tradeRules:'rules',tradeEmotion:'emotion',tradeNotes:'notes'}; Object.entries(map).forEach(([field,key])=>{if(t[key]!==undefined&&t[key]!==null)$(field).value=t[key]}); currentImageData=t.image||'';if(currentImageData){$('imagePreview').src=currentImageData;$('imagePreview').hidden=false;} } $('tradeDialog').showModal(); }
function formValue(id) { return $(id).value.trim(); }
$('tradeForm').addEventListener('submit',e=>{e.preventDefault();const id=formValue('tradeId'),status=formValue('tradeStatus'),exit=formValue('tradeExit');if(status==='Closed'&&exit===''){toast('Add an exit price for a closed trade, or mark it Open.');return;}const t={id:id||uid(),createdAt:Date.now(),pair:formValue('tradePair').toUpperCase().replace(/\s/g,''),market:formValue('tradeMarket'),side:formValue('tradeSide'),status,setup:formValue('tradeSetup'),timeframe:formValue('tradeTimeframe'),entry:formValue('tradeEntry'),exit,qty:formValue('tradeQty'),leverage:formValue('tradeLeverage'),stop:formValue('tradeStop'),target:formValue('tradeTarget'),fees:formValue('tradeFees')||'0',manualPnl:formValue('tradeManualPnl'),risk:formValue('tradeRisk'),date:formValue('tradeDate'),rules:formValue('tradeRules'),emotion:formValue('tradeEmotion'),notes:formValue('tradeNotes'),image:currentImageData};if(t.status==='Closed'&&t.manualPnl===''&&t.qty==='' ){toast('Enter position quantity or manual net P/L to calculate results.');return;}if(id){const i=trades.findIndex(x=>x.id===id);if(i>=0)trades[i]=t;}else trades.push(t);if(!persist())return;$('tradeDialog').close();renderAll();toast(id?'Trade updated.':'Trade saved.');});
$('deleteTradeBtn').addEventListener('click',()=>{const id=formValue('tradeId');if(id&&confirm('Delete this trade permanently from this browser?')){trades=trades.filter(t=>t.id!==id);persist();$('tradeDialog').close();renderAll();toast('Trade deleted.');}});
$('tradeImage').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>1200000){toast('Image is over 1.2 MB. Please compress it first to protect browser storage.');e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{currentImageData=reader.result;$('imagePreview').src=currentImageData;$('imagePreview').hidden=false;};reader.readAsDataURL(f);});
function resetReviewForm(){ $('reviewForm').reset();$('reviewId').value='';$('reviewDate').value=new Date().toISOString().slice(0,10); }
$('reviewForm').addEventListener('submit',e=>{e.preventDefault();const id=formValue('reviewId');const r={id:id||uid(),date:formValue('reviewDate'),mood:formValue('reviewMood'),adherence:formValue('reviewAdherence'),mistake:formValue('reviewMistake'),good:formValue('reviewGood'),improve:formValue('reviewImprove'),lesson:formValue('reviewLesson')};if(id){const i=reviews.findIndex(x=>x.id===id);if(i>=0)reviews[i]=r;}else reviews.push(r);persist();renderReviews();resetReviewForm();toast('Daily review saved.');});
function editReview(id){const r=reviews.find(x=>x.id===id);if(!r)return;$('reviewId').value=r.id;$('reviewDate').value=r.date;$('reviewMood').value=r.mood;$('reviewAdherence').value=r.adherence;$('reviewMistake').value=r.mistake;$('reviewGood').value=r.good;$('reviewImprove').value=r.improve;$('reviewLesson').value=r.lesson;window.scrollTo({top:0,behavior:'smooth'});}
$('resetReview').onclick=resetReviewForm;$('newReviewBtn').onclick=()=>{resetReviewForm();$('reviewDate').value=new Date().toISOString().slice(0,10);$('reviewGood').focus();};$('quickReviewBtn').onclick=()=>{navigate('reviews');resetReviewForm();};$('shortcutReview').onclick=()=>{navigate('reviews');resetReviewForm();};
$('riskForm').addEventListener('submit',e=>{e.preventDefault();const balance=num($('riskBalance').value),riskPct=num($('riskPercent').value)/100,entry=num($('riskEntry').value),stop=num($('riskStop').value),target=num($('riskTarget').value),feePct=num($('riskFee').value)/100;if(balance<=0||entry<=0||stop<=0||entry===stop||riskPct<=0||riskPct>1){toast('Check balance, risk, entry, and stop-loss values.');return;}const distance=Math.abs(entry-stop)/entry;const riskAmount=balance*riskPct;const riskPerUnit=Math.abs(entry-stop)+entry*feePct+stop*feePct;const qty=riskAmount/riskPerUnit;const notional=qty*entry;const reward=target>0?Math.abs(target-entry)*qty-(entry+target)*qty*feePct:null;const rr=target>0?Math.abs(target-entry)/(Math.abs(entry-stop)||1):null;$('riskAmount').innerHTML=money(riskAmount)+`<small>USDT planned risk · ${pct(riskPct*100)}</small>`;$('riskNotional').textContent=money(notional);$('riskQuantity').textContent=qty.toLocaleString('en-US',{maximumFractionDigits:8});$('riskReward').textContent=reward===null?'—':money(reward);$('riskRR').textContent=rr===null?'—':'1 : '+rr.toFixed(2);});
function exportData(){const blob=new Blob([JSON.stringify({app:'Edge Journal',version:1,exportedAt:new Date().toISOString(),trades,reviews},null,2)],{type:'application/json'});downloadBlob(blob,`edge-journal-backup-${new Date().toISOString().slice(0,10)}.json`);toast('Backup exported. Keep it somewhere private.');}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function exportCSV(){const cols=['date','pair','market','side','status','setup','timeframe','entry','exit','qty','leverage','stop','target','fees','netPnl','risk','rules','emotion','notes'];const rows=[cols.join(','),...trades.map(t=>cols.map(k=>{let v=k==='netPnl'?calcPnl(t):t[k]??'';return '"'+String(v).replace(/"/g,'""')+'"';}).join(','))];downloadBlob(new Blob([rows.join('\r\n')],{type:'text/csv;charset=utf-8'}),`edge-journal-trades-${new Date().toISOString().slice(0,10)}.csv`);toast('Trade CSV exported.');}
$('exportBtn').onclick=exportData;$('analyticsExport').onclick=exportCSV;$('importBtn').onclick=()=>$('importFile').click();$('importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const text=await f.text();if(f.name.toLowerCase().endsWith('.csv')){toast('CSV export is supported; import JSON backups to restore records.');return;}const data=JSON.parse(text);if(!Array.isArray(data.trades))throw new Error('Invalid backup');if(!confirm(`Import ${data.trades.length} trades and ${(data.reviews||[]).length} reviews? Existing records will be merged by ID.`))return;const merge=(old,inc)=>{const m=new Map(old.map(x=>[x.id,x]));inc.forEach(x=>m.set(x.id||uid(),x));return [...m.values()];};trades=merge(trades,data.trades);reviews=merge(reviews,data.reviews||[]);persist();renderAll();toast('Backup imported and merged.');}catch(err){toast('Could not read this backup file.');}finally{e.target.value='';}});
$('githubBtn').onclick=()=>openGitHubSettings();
$('githubOpenBtn').onclick=()=>{const cfg=getGitHubConfig();window.open(cfg?.pagesUrl||repoUrl(cfg),'_blank','noopener,noreferrer');};
$('githubTestBtn').addEventListener('click',async()=>{const cfg=readGitHubForm();try{await testGitHubConnection(cfg);}catch(err){setGitHubStatus(err.message,'error');toast('Test koneksi gagal: '+err.message);}});
$('githubForm').addEventListener('submit',saveGitHubSettings);
$('newTradeTop').onclick=()=>openTrade();$('newTradePage').onclick=()=>openTrade();$('emptyAddTrade').onclick=()=>openTrade();$('emptyAddTrade2').onclick=()=>openTrade();$('shortcutTrade').onclick=()=>openTrade();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>navigate(b.dataset.goto));['tradeSearch','filterSide','filterStatus','filterResult'].forEach(id=>$(id).addEventListener(id==='tradeSearch'?'input':'change',renderTrades));$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');document.addEventListener('click',e=>{if(window.innerWidth<=800&&$('sidebar').classList.contains('open')&&!$('sidebar').contains(e.target)&&!$('mobileMenu').contains(e.target))$('sidebar').classList.remove('open');});
function renderAll(){renderDashboard();renderTrades();renderAnalytics();renderReviews();}
function compactMoney(v){if(!Number.isFinite(Number(v)))return '—';const n=Number(v);if(Math.abs(n)>=1e12)return '$'+(n/1e12).toFixed(2)+'T';if(Math.abs(n)>=1e9)return '$'+(n/1e9).toFixed(2)+'B';if(Math.abs(n)>=1e6)return '$'+(n/1e6).toFixed(2)+'M';if(Math.abs(n)>=1e3)return '$'+(n/1e3).toFixed(2)+'K';return '$'+n.toLocaleString('en-US',{maximumFractionDigits:2});}
function marketPrice(v){if(!Number.isFinite(Number(v)))return '—';return '$'+Number(v).toLocaleString('en-US',{maximumFractionDigits:Number(v)<1?8:2});}
async function loadMarket(){if(marketLoading)return;marketLoading=true;const body=$('marketBody');$('marketError').hidden=true;$('marketUpdated').textContent='Fetching latest available data…';$('refreshMarketBtn').disabled=true;body.innerHTML='<tr><td colspan="7" class="market-message">Loading top market data…</td></tr>';try{const res=await fetch('https://api.coinpaprika.com/v1/tickers?quotes=USD',{headers:{'accept':'application/json'}});if(!res.ok)throw new Error('Market provider returned HTTP '+res.status);const data=await res.json();marketCoins=data.filter(c=>c.rank>0&&c.quotes&&c.quotes.USD).sort((a,b)=>a.rank-b.rank).slice(0,100);if(!marketCoins.length)throw new Error('No market data was returned.');$('marketUpdated').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})+' · refreshes every 90 seconds';renderMarket();}catch(err){body.innerHTML='<tr><td colspan="7" class="market-message">Could not load market data.</td></tr>';$('marketError').hidden=false;$('marketError').textContent='Market data could not be fetched. Check your connection or try again later. '+err.message;$('marketUpdated').textContent='Market data unavailable';}finally{marketLoading=false;$('refreshMarketBtn').disabled=false;}}
function renderMarket(){const q=($('marketSearch')?.value||'').trim().toLowerCase(),limit=Number($('marketLimit')?.value||50);const list=marketCoins.filter(c=>!q||c.name.toLowerCase().includes(q)||c.symbol.toLowerCase().includes(q)).slice(0,limit);$('marketBody').innerHTML=list.length?list.map(c=>{const quote=c.quotes.USD,change=Number(quote.percent_change_24h||0),watched=watchedCoins.includes(c.id);return `<tr><td class="market-rank">${c.rank}</td><td><div class="market-asset">${c.logo?`<img class="coin-icon" src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.style.display='none'">`:`<span class="coin-icon">${esc(c.symbol.slice(0,3))}</span>`}<span><b>${esc(c.name)}</b><small>${esc(c.symbol)} · ${esc(c.id)}</small></span></div></td><td class="market-price">${marketPrice(quote.price)}</td><td class="${change>=0?'market-positive':'market-negative'}">${change>0?'+':''}${change.toFixed(2)}%</td><td class="market-number">${compactMoney(quote.market_cap)}</td><td class="market-number">${compactMoney(quote.volume_24h)}</td><td><button class="watch-btn ${watched?'is-watched':''}" data-watch="${esc(c.id)}" title="Toggle watchlist">${watched?'★':'☆'}</button> <button class="use-coin-btn" data-use-coin="${esc(c.symbol)}" title="Use in a new trade">＋ Trade</button></td></tr>`}).join(''):'<tr><td colspan="7" class="market-message">No coins match your search.</td></tr>';document.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{const id=b.dataset.watch;watchedCoins=watchedCoins.includes(id)?watchedCoins.filter(x=>x!==id):[...watchedCoins,id];try{localStorage.setItem('edgeJournal.watchlist.v1',JSON.stringify(watchedCoins))}catch{}renderMarket();});document.querySelectorAll('[data-use-coin]').forEach(b=>b.onclick=()=>{const c=marketCoins.find(x=>x.symbol.toLowerCase()===b.dataset.useCoin.toLowerCase());if(c){$('tradePair').value=c.symbol.toUpperCase()+'/USDT';$('tradeDialog').showModal();}});}
$('refreshMarketBtn').addEventListener('click',loadMarket);$('marketLimit').addEventListener('change',renderMarket);$('marketSearch').addEventListener('input',renderMarket);setInterval(()=>{if(document.visibilityState==='visible'&&document.getElementById('view-market').classList.contains('active'))loadMarket()},90000);
function exportJournalPDF(){if(!window.jspdf||!window.jspdf.jsPDF){toast('PDF library did not load. Check internet connection and retry.');return;}const doc=new window.jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a4'});const closed=closedTrades(),net=closed.reduce((s,t)=>s+calcPnl(t),0),wins=closed.filter(t=>calcPnl(t)>0).length,losses=closed.filter(t=>calcPnl(t)<0).length;const now=new Date();doc.setFillColor(11,14,17);doc.rect(0,0,297,36,'F');doc.setTextColor(104,214,155);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('EDGE JOURNAL',14,15);doc.setTextColor(232,237,242);doc.setFontSize(10);doc.text('CRYPTO TRADING JOURNAL · PERFORMANCE REPORT',14,23);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Generated '+now.toLocaleString(),14,30);doc.setTextColor(20,30,25);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('PERFORMANCE SUMMARY',14,46);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`Total trades: ${trades.length}    Closed: ${closed.length}    Wins: ${wins}    Losses: ${losses}    Win rate: ${closed.length?(wins/closed.length*100).toFixed(1)+'%':'—'}    Net P/L: ${net.toFixed(2)} USDT`,14,53);const rows=trades.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(t=>[t.date||'—',t.pair||'—',t.market||'—',t.side||'—',t.setup||'—',t.timeframe||'—',t.entry??'—',t.exit||'—',t.status||'—',t.status==='Closed'?calcPnl(t).toFixed(2):'—',t.emotion||'—',t.rules||'—']);doc.autoTable({startY:60,head:[['Date','Pair','Market','Side','Setup','TF','Entry','Exit','Status','Net P/L (USDT)','Emotion','Plan']],body:rows,theme:'grid',styles:{font:'helvetica',fontSize:7,cellPadding:2.2,textColor:[40,48,55],lineColor:[220,226,230],lineWidth:.15,overflow:'linebreak'},headStyles:{fillColor:[23,58,43],textColor:[235,247,240],fontStyle:'bold'},alternateRowStyles:{fillColor:[245,248,246]},columnStyles:{9:{halign:'right'}} ,margin:{left:12,right:12}});let y=(doc.lastAutoTable?.finalY||60)+10;if(reviews.length){if(y>175){doc.addPage();y=18;}doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('DAILY REVIEW NOTES',14,y);y+=5;const reviewRows=reviews.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(r=>[r.date||'—',r.mood||'—',r.adherence||'—',r.mistake||'—',r.good||'',r.improve||'',r.lesson||'']);doc.autoTable({startY:y,head:[['Date','Mood','Plan adherence','Main mistake','Went well','Improve','Lesson']],body:reviewRows,theme:'grid',styles:{font:'helvetica',fontSize:7,cellPadding:2.2,overflow:'linebreak'},headStyles:{fillColor:[23,58,43],textColor:[255,255,255]},margin:{left:12,right:12}});}const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFontSize(7);doc.setTextColor(120);doc.text('PRIVATE · Personal trading records',12,202);doc.text(`Page ${i} / ${pages}`,285,202,{align:'right'});}doc.save('edge-journal-report-'+now.toISOString().slice(0,10)+'.pdf');toast('PDF report generated.');}
$('journalPdfBtn').addEventListener('click',exportJournalPDF);
$('todayDate').textContent=new Date().toLocaleDateString('en-US',{weekday:'short',month:'short',day:'2-digit',year:'numeric'});$('reviewDate').value=new Date().toISOString().slice(0,10);renderAll();const savedGitHubConfig=getGitHubConfig();if(savedGitHubConfig?.token&&savedGitHubConfig?.owner&&savedGitHubConfig?.repo){syncJournalFromGitHub({quiet:true});if(savedGitHubConfig.pagesUrl)$('githubBtn').innerHTML='⚙ Pengaturan GitHub <span>↗</span>'; $('githubOpenBtn').innerHTML='◉ Buka Repository <span>↗</span>';}
